#!/usr/bin/with-contenv bash
set -e

vecho () { if [ "${S6_VERBOSITY:-1}" -gt 0 ]; then echo "[$0] $@"; fi; }

PHPMAJMIN="${PHPMAJMIN:-82}"; # set in Dockerfile

ROOTDIR="${ROOTDIR:-/config}";
PHPDIR="${PHPDIR:-/etc/php$PHPMAJMIN}";
PHPCONFDIR="${PHPCONFDIR:-$PHPDIR/conf.d}";

# make our folders
vecho "Ensure configuration directories exist.";
mkdir -p \
    $PHPDIR \
    $PHPCONFDIR \
    ;

if [ ! -f "$PHPDIR/php.ini" ];
then
    vecho "Setting up /defaults/php.ini as $PHPDIR/php.ini";
    sed \
        -Ee "s#^;?(date.timezone) =.*#\1 = ${TZ:-UTC}#g" \
        -Ee "s#^;?(max_execution_time) =.*#\1 = ${PHP_MAX_EXECUTION_TIME:-30}#g" \
        -Ee "s#^;?(max_file_uploads) = .*#\1 = ${PHP_MAX_FILE_UPLOADS:-20}#g" \
        -Ee "s#^;?(memory_limit) =.*#\1 = ${PHP_MEMORY_LIMIT:-128M}#g" \
        -Ee "s#^;?(post_max_size) = .*#\1 = ${PHP_POST_MAX_SIZE:-16M}#g" \
        -Ee "s#^;?(upload_max_filesize) = .*#\1 = ${PHP_UPLOAD_MAX_FILESIZE:-16M}#g" \
        \
        -Ee "s#^;?(opcache.enable_cli)=.*#\1 = ${PHP_OPCACHE_ENABLE_CLI:-0}#g" \
        \
    /defaults/php.ini > $PHPDIR/php.ini;
        # -Ee "s#^;?(opcache.fast_shutdown)=.*#\1 = ${PHP_OPCACHE_FAST_SHUTDOWN:-1}#g" \
    #
fi;

# fix permissions
if [ -z "${PHP_SKIP_PERMFIX}" ]; # may set to 'true' for if configurations are mounted read-only
then
    vecho "Fixing permissions.";
    chown -R \
        ${S6_USER:-alpine}:${PGID:-1000} \
        $PHPDIR \
        $PHPCONFDIR \
        ;
fi;
