#!/usr/bin/with-contenv bash
set -e

CROND_ARGS="${CROND_ARGS:- -f -S -l 5}";
CROND_CONF="${CROND_CONF:-/etc/crontabs}";

if [ -z "${SKIP_CRON}" ];
then
    echo "Using ${CROND_CONF} for cron cronfiguration...";
    exec \
        /usr/sbin/crond ${CROND_ARGS} -c ${CROND_CONF}
else
    echo "Skip starting cron.";
    sleep infinity;
fi;
