#!/usr/bin/with-contenv bash
set -e

PHPMAJMIN="${PHPMAJMIN:-82}"; # set in Dockerfile
PHPDIR="${PHPDIR:-/etc/php$PHPMAJMIN}";
PHPFPMCONF="${PHPFPMCONF:-$PHPDIR/php-fpm.conf}";
PHPFPM_ARGS="${PHPFPM_ARGS:- -F}";

exec \
    /usr/sbin/php-fpm${PHPMAJMIN} \
    -c "${PHPDIR}" \
    -y "${PHPFPMCONF}" \
    ${PHPFPM_ARGS}
